<script lang="ts" module>
	import { defineMeta } from '@storybook/addon-svelte-csf';

	const { Story } = defineMeta({
		title: 'MODE_BASE/book',
		parameters: {
			docs: {
				description: {
					component:
						'Math-backed books generated by `run_fixtures.py` + `export_storybook_fixtures.py` in the math-sdk. Each named story tests a specific mechanic. **random** cycles through 50 real simulation books.',
				},
			},
		},
	});
</script>

<script lang="ts">
	import {
		StoryGameTemplate,
		StoryLocale,
		type TemplateArgs,
		templateArgs,
	} from 'components-storybook';
	import { randomInteger } from 'utils-shared/random';

	import Game from '../components/Game.svelte';
	import { setContext } from '../game/context';
	import { playBet } from '../game/utils';
	import books from './data/base_books';
	import { goldenBaseBook } from './data/golden_base_book';
	import noWin from './data/math_fixtures/base_no_win.json';
	import oneCluster from './data/math_fixtures/base_one_cluster.json';
	import twoCascades from './data/math_fixtures/base_two_cascades.json';
	import multiTumble from './data/math_fixtures/base_multi_tumble.json';
	import kronosStrike from './data/math_fixtures/base_kronos_strike.json';

	setContext();
</script>

{#snippet template(args: TemplateArgs<any>)}
	<StoryGameTemplate
		skipLoadingScreen={args.skipLoadingScreen}
		action={async () => {
			await args.action?.(args.data);
		}}
	>
		<StoryLocale lang="en">
			<Game />
		</StoryLocale>
	</StoryGameTemplate>
{/snippet}

<Story
	name="random"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const index = randomInteger({ min: 0, max: books.length - 1 });
			const data = books[index] as any;
			console.log('Running math book at index', index);
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Picks a random book from the 50-book math pool. All books are real Kronos Cluster simulations (base-game, no FS).',
			},
		},
	}}
	{template}
/>

<Story
	name="fixture — no win"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const data = noWin as any;
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Zero-win base spin: board revealed, no clusters ≥ 5. Expect: reveal → setTotalWin 0 → finalWin 0. Verifies the idle/lose path and that no multiplier grid appears.',
			},
		},
	}}
	{template}
/>

<Story
	name="fixture — one cluster"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const data = oneCluster as any;
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Single winning cluster: one winInfo → updateGrid stamps 2× cells → kronosBar advances → tumbleBoard → no second win → finalWin. Verifies one tumble step and multiplier grid.',
			},
		},
	}}
	{template}
/>

<Story
	name="fixture — two cascades"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const data = twoCascades as any;
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Two consecutive winning clusters: grid overlays stack (2× → 4× on revisited cells), bar advances twice. Verifies clusterMult accumulation across tumbles.',
			},
		},
	}}
	{template}
/>

<Story
	name="fixture — multi tumble"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const data = multiTumble as any;
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Three or more winning tumble steps. Multiplier overlays compound across the board. Verifies deep cascading and running tumble win display.',
			},
		},
	}}
	{template}
/>

<Story
	name="fixture — kronos strike"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			const data = kronosStrike as any;
			await playBet({ ...data, state: data.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Kronos bar fills completely: kronosBar filled=true → kronosStrike hits random cells with high multipliers → bar resets → tumble continues. Verifies the full strike sequence.',
			},
		},
	}}
	{template}
/>

<Story
	name="golden — base + free spins"
	args={templateArgs({
		skipLoadingScreen: true,
		data: {},
		action: async () => {
			await playBet({ ...goldenBaseBook, state: goldenBaseBook.events });
		},
	})}
	parameters={{
		docs: {
			description: {
				story:
					'Hand-authored reference: base tumbles + bar fill/strike + free-spin trigger and multiple FS spins with persistent multiplier overlays. The only story that exercises the full FS flow.',
			},
		},
	}}
	{template}
/>
