const regularLowSymbols = {
	RUNE: {
		paytable: [{ '5': 5 }, { '4': 1 }, { '3': 0.5 }],
	},
	SHIELD: {
		paytable: [{ '5': 3 }, { '4': 0.7 }, { '3': 0.3 }],
	},
	HELMET: {
		paytable: [{ '5': 2 }, { '4': 0.5 }, { '3': 0.2 }],
	},
};

const regularMidSymbols = {
	EAGLE: {
		paytable: [{ '5': 10 }, { '4': 3 }, { '3': 2 }],
	},
	PEGASUS: {
		paytable: [{ '5': 15 }, { '4': 5 }, { '3': 3 }],
	},
};

const symbols = {
	...regularLowSymbols,
	...regularMidSymbols,
	KRONOS_SMALL: {
		paytable: [{ '5': 50 }, { '4': 20 }, { '3': 10 }],
	},
	SCATTER: {
		special_properties: ['scatter'],
	},
	CHEST: {
		special_properties: ['chest'],
	},
	WILD: {
		special_properties: ['wild'],
	},
	WILD_LIGHTNING: {
		special_properties: ['wild', 'powerup_lightning'],
	},
	WILD_SURGE: {
		special_properties: ['wild', 'powerup_surge'],
	},
	WILD_HAMMER: {
		special_properties: ['wild', 'powerup_hammer'],
	},
	WILD_EAGLE: {
		special_properties: ['wild', 'powerup_lightning', 'powerup_surge', 'powerup_hammer'],
	},
};

const reel1 = [
	{ name: 'RUNE' },
	{ name: 'SHIELD' },
	{ name: 'HELMET' },
	{ name: 'RUNE' },
	{ name: 'EAGLE' },
	{ name: 'WILD', wild: true },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'RUNE' },
	{ name: 'SHIELD' },
	{ name: 'HELMET' },
	{ name: 'PEGASUS' },
	{ name: 'RUNE' },
	{ name: 'SCATTER', scatter: true },
	{ name: 'SHIELD' },
	{ name: 'HELMET' },
	{ name: 'WILD_LIGHTNING', wild: true },
	{ name: 'RUNE' },
	{ name: 'KRONOS_SMALL' },
	{ name: 'SHIELD' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'SHIELD' },
	{ name: 'HELMET' },
	{ name: 'EAGLE' },
	{ name: 'WILD_SURGE', wild: true },
	{ name: 'RUNE' },
	{ name: 'WILD_EAGLE', wild: true },
];

const reel2 = [
	{ name: 'SHIELD' },
	{ name: 'RUNE' },
	{ name: 'HELMET' },
	{ name: 'WILD', wild: true },
	{ name: 'PEGASUS' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'RUNE' },
	{ name: 'EAGLE' },
	{ name: 'SHIELD' },
	{ name: 'WILD_LIGHTNING', wild: true },
	{ name: 'HELMET' },
	{ name: 'SCATTER', scatter: true },
	{ name: 'RUNE' },
	{ name: 'WILD_SURGE', wild: true },
	{ name: 'SHIELD' },
	{ name: 'KRONOS_SMALL' },
	{ name: 'HELMET' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'HELMET' },
	{ name: 'EAGLE' },
	{ name: 'RUNE' },
	{ name: 'WILD_HAMMER', wild: true },
	{ name: 'SHIELD' },
	{ name: 'PEGASUS' },
	{ name: 'WILD_EAGLE', wild: true },
];

const reel3 = [
	{ name: 'HELMET' },
	{ name: 'PEGASUS' },
	{ name: 'RUNE' },
	{ name: 'WILD', wild: true },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'RUNE' },
	{ name: 'SHIELD' },
	{ name: 'SCATTER', scatter: true },
	{ name: 'EAGLE' },
	{ name: 'WILD_LIGHTNING', wild: true },
	{ name: 'RUNE' },
	{ name: 'HELMET' },
	{ name: 'WILD_SURGE', wild: true },
	{ name: 'SHIELD' },
	{ name: 'KRONOS_SMALL' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'SHIELD' },
	{ name: 'PEGASUS' },
	{ name: 'HELMET' },
	{ name: 'WILD_HAMMER', wild: true },
	{ name: 'RUNE' },
	{ name: 'EAGLE' },
	{ name: 'WILD_EAGLE', wild: true },
];

const reel4 = [
	{ name: 'EAGLE' },
	{ name: 'HELMET' },
	{ name: 'SHIELD' },
	{ name: 'WILD', wild: true },
	{ name: 'RUNE' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'HELMET' },
	{ name: 'PEGASUS' },
	{ name: 'SCATTER', scatter: true },
	{ name: 'WILD_LIGHTNING', wild: true },
	{ name: 'RUNE' },
	{ name: 'SHIELD' },
	{ name: 'WILD_SURGE', wild: true },
	{ name: 'HELMET' },
	{ name: 'KRONOS_SMALL' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'RUNE' },
	{ name: 'EAGLE' },
	{ name: 'WILD_HAMMER', wild: true },
	{ name: 'SHIELD' },
	{ name: 'RUNE' },
	{ name: 'PEGASUS' },
	{ name: 'WILD_EAGLE', wild: true },
];

const reel5 = [
	{ name: 'KRONOS_SMALL' },
	{ name: 'RUNE' },
	{ name: 'HELMET' },
	{ name: 'SHIELD' },
	{ name: 'EAGLE' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'RUNE' },
	{ name: 'PEGASUS' },
	{ name: 'WILD', wild: true },
	{ name: 'SCATTER', scatter: true },
	{ name: 'SHIELD' },
	{ name: 'HELMET' },
	{ name: 'RUNE' },
	{ name: 'EAGLE' },
	{ name: 'CHEST', chestActive: false, underlyingSymbol: 'SHIELD' },
	{ name: 'WILD_HAMMER', wild: true },
	{ name: 'PEGASUS' },
	{ name: 'RUNE' },
	{ name: 'HELMET' },
	{ name: 'SHIELD' },
	{ name: 'SCATTER', scatter: true },
	{ name: 'RUNE' },
	{ name: 'WILD_LIGHTNING', wild: true },
	{ name: 'EAGLE' },
	{ name: 'WILD_EAGLE', wild: true },
];

export default {
	providerName: 'sample_provider',
	gameName: 'clash_of_kronos',
	gameID: '0_0_clash_of_kronos',
	rtp: 0.96,
	targetRtp: 0.96,
	numReels: 5,
	numRows: [3, 3, 3, 3, 3],
	betModes: {
		base: {
			cost: 1.0,
			feature: true,
			buyBonus: false,
			rtp: 0.96,
			max_win: 10000.0,
		},
		bonus: {
			cost: 100.0,
			feature: false,
			buyBonus: true,
			rtp: 0.96,
			max_win: 10000.0,
		},
	},
	paylines: {
		'1': [0, 0, 0, 0, 0],
		'2': [1, 1, 1, 1, 1],
		'3': [2, 2, 2, 2, 2],
		'4': [0, 1, 2, 1, 0],
		'5': [2, 1, 0, 1, 2],
		'6': [0, 0, 1, 2, 2],
		'7': [2, 2, 1, 0, 0],
		'8': [1, 0, 1, 2, 1],
		'9': [1, 2, 1, 0, 1],
		'10': [0, 1, 1, 1, 2],
		'11': [2, 1, 1, 1, 0],
		'12': [0, 1, 0, 1, 2],
		'13': [2, 1, 2, 1, 0],
		'14': [1, 1, 0, 1, 1],
		'15': [1, 1, 2, 1, 1],
		'16': [0, 2, 1, 0, 2],
		'17': [2, 0, 1, 2, 0],
		'18': [0, 0, 2, 0, 0],
		'19': [2, 2, 0, 2, 2],
		'20': [1, 0, 0, 0, 1],
		'21': [1, 2, 2, 2, 1],
		'22': [0, 2, 0, 2, 0],
		'23': [2, 0, 2, 0, 2],
		'24': [0, 1, 2, 2, 2],
		'25': [2, 1, 0, 0, 0],
		'26': [1, 0, 2, 0, 1],
		'27': [1, 2, 0, 2, 1],
		'28': [0, 0, 0, 1, 2],
		'29': [2, 2, 2, 1, 0],
		'30': [1, 0, 1, 2, 1],
	},
	symbols,
	paddingReels: {
		basegame: [reel1, reel2, reel3, reel4, reel5],
		freegame: [reel1, reel2, reel3, reel4, reel5],
	},
} as const;
