/**
 * Math-backed base-game book pool for Storybook.
 *
 * Generated by:
 *   cd math-sdk/games/0_0_clash_kronos_cluster
 *   python run_fixtures.py
 *   python export_storybook_fixtures.py
 *
 * 50 real simulation books (no wilds, cell-multiplier cluster pays, Kronos bar).
 * Regenerate whenever math logic or reels change.
 */
import pool from './math_fixtures/base_pool.json';

export default pool as { gameType: string; events: object[] }[];
