/**
 * Math-backed bonus (free-spin) book pool for Storybook.
 *
 * Generated by math-sdk only (never hand-authored — inconsistent books freeze tumbles):
 *   cd math-sdk/games/0_0_clash_kronos_cluster
 *   FIXTURE_BONUS_SIMS=10 python run_fixtures.py   # optional; default 0 skips slow FS sims
 *   python export_storybook_fixtures.py --bonus-only
 *
 * Pool is empty until you run with FIXTURE_BONUS_SIMS>0 and export.
 */
import pool from './math_fixtures/bonus_pool.json';

export default pool as { gameType: string; events: object[] }[];
