import type { BookEvent } from '../../game/typesBookEvent';

// Generated by math-sdk/games/0_0_clash_of_kronos/storybook_fixtures.py.
// Edit the generator instead of this file.
const events = {
	"reveal": {
		"index": 0,
		"type": "reveal",
		"board": [
			[
				{
					"name": "HELMET"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "SHIELD"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "EAGLE"
				}
			],
			[
				{
					"name": "SHIELD"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "PEGASUS"
				}
			],
			[
				{
					"name": "PEGASUS"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "EAGLE"
				},
				{
					"name": "HELMET"
				}
			],
			[
				{
					"name": "EAGLE"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "PEGASUS"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "SHIELD"
				}
			],
			[
				{
					"name": "KRONOS_SMALL"
				},
				{
					"name": "SHIELD"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "HELMET"
				}
			]
		],
		"paddingPositions": [
			0,
			0,
			0,
			0,
			0
		],
		"anticipation": [
			0,
			0,
			0,
			0,
			0
		],
		"gameType": "basegame"
	},
	"cascadeTrackerUpdate": {
		"index": 19,
		"type": "cascadeTrackerUpdate",
		"stage": 5,
		"multiplier": 2,
		"gameType": "basegame",
		"chestsActive": true
	},
	"chestUnlock": {
		"index": 14,
		"type": "chestUnlock",
		"positions": [
			{
				"reel": 0,
				"row": 3
			},
			{
				"reel": 2,
				"row": 2
			},
			{
				"reel": 4,
				"row": 2
			}
		]
	},
	"chestValuesUpdate": {
		"index": 15,
		"type": "chestValuesUpdate",
		"updates": [
			{
				"position": {
					"reel": 0,
					"row": 3
				},
				"value": 75,
				"active": true
			},
			{
				"position": {
					"reel": 2,
					"row": 2
				},
				"value": 120,
				"active": true
			},
			{
				"position": {
					"reel": 4,
					"row": 2
				},
				"value": 200,
				"active": true
			}
		]
	},
	"winInfo": {
		"index": 2,
		"type": "winInfo",
		"totalWin": 500,
		"wins": [
			{
				"symbol": "RUNE",
				"kind": 5,
				"win": 500,
				"positions": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 3,
						"row": 1
					},
					{
						"reel": 4,
						"row": 1
					}
				],
				"meta": {
					"lineIndex": 2,
					"multiplier": 1,
					"winWithoutMult": 500,
					"globalMult": 1,
					"lineMultiplier": 1,
					"trackerStage": 1,
					"trackerMultiplier": 1
				}
			}
		]
	},
	"updateTumbleWin": {
		"index": 3,
		"type": "updateTumbleWin",
		"amount": 50
	},
	"tumbleBoard": {
		"index": 4,
		"type": "tumbleBoard",
		"explodingSymbols": [
			{
				"reel": 0,
				"row": 1
			},
			{
				"reel": 1,
				"row": 1
			},
			{
				"reel": 2,
				"row": 1
			}
		],
		"newSymbols": [
			[
				{
					"name": "PEGASUS"
				}
			],
			[
				{
					"name": "EAGLE"
				}
			],
			[
				{
					"name": "HELMET"
				}
			],
			[],
			[]
		]
	},
	"lightningStrike": {
		"index": 5,
		"type": "lightningStrike",
		"strikes": [
			{
				"position": {
					"reel": 1,
					"row": 2
				},
				"toSymbol": {
					"name": "WILD",
					"wild": true
				}
			},
			{
				"position": {
					"reel": 3,
					"row": 3
				},
				"toSymbol": {
					"name": "WILD",
					"wild": true
				}
			},
			{
				"position": {
					"reel": 4,
					"row": 1
				},
				"toSymbol": {
					"name": "WILD",
					"wild": true
				}
			}
		]
	},
	"surgeChests": {
		"index": 19,
		"type": "surgeChests",
		"updates": [
			{
				"position": {
					"reel": 0,
					"row": 3
				},
				"from": 75,
				"to": 125
			},
			{
				"position": {
					"reel": 2,
					"row": 2
				},
				"from": 120,
				"to": 180
			},
			{
				"position": {
					"reel": 4,
					"row": 2
				},
				"from": 200,
				"to": 300
			}
		]
	},
	"hammerCollect": {
		"index": 5,
		"type": "hammerCollect",
		"position": {
			"reel": 4,
			"row": 1
		}
	},
	"hammerSmash": {
		"index": 6,
		"type": "hammerSmash",
		"clearedPositions": [
			{
				"reel": 0,
				"row": 0
			},
			{
				"reel": 1,
				"row": 2
			},
			{
				"reel": 2,
				"row": 3
			},
			{
				"reel": 3,
				"row": 1
			}
		],
		"newSymbols": [
			[
				{
					"name": "PEGASUS"
				},
				{
					"name": "HELMET"
				}
			],
			[
				{
					"name": "EAGLE"
				}
			],
			[
				{
					"name": "RUNE"
				}
			],
			[
				{
					"name": "SHIELD"
				}
			],
			[]
		],
		"resultBoard": [
			[
				{
					"name": "HELMET"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "SHIELD"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "EAGLE"
				}
			],
			[
				{
					"name": "SHIELD"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "PEGASUS"
				}
			],
			[
				{
					"name": "PEGASUS"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "EAGLE"
				},
				{
					"name": "HELMET"
				}
			],
			[
				{
					"name": "EAGLE"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "PEGASUS"
				},
				{
					"name": "HELMET"
				},
				{
					"name": "SHIELD"
				}
			],
			[
				{
					"name": "KRONOS_SMALL"
				},
				{
					"name": "RUNE"
				},
				{
					"name": "CHEST",
					"chestActive": false,
					"underlyingSymbol": "RUNE"
				},
				{
					"name": "SHIELD"
				},
				{
					"name": "HELMET"
				}
			]
		],
		"trackerStage": 2,
		"trackerMultiplier": 1
	},
	"freeSpinTrigger": {
		"index": 1,
		"type": "freeSpinTrigger",
		"totalFs": 8,
		"positions": [
			{
				"reel": 0,
				"row": 1
			},
			{
				"reel": 2,
				"row": 1
			},
			{
				"reel": 4,
				"row": 1
			}
		]
	},
	"freeSpinRetrigger": {
		"index": 2,
		"type": "freeSpinRetrigger",
		"totalFs": 5,
		"positions": [
			{
				"reel": 0,
				"row": 1
			},
			{
				"reel": 2,
				"row": 1
			},
			{
				"reel": 4,
				"row": 1
			}
		]
	},
	"updateFreeSpin": {
		"index": 0,
		"type": "updateFreeSpin",
		"amount": 2,
		"total": 8
	},
	"setTotalWin": {
		"index": 4,
		"type": "setTotalWin",
		"amount": 50
	},
	"setWin": {
		"index": 5,
		"type": "setWin",
		"amount": 50,
		"winLevel": 1
	},
	"freeSpinEnd": {
		"index": 7,
		"type": "freeSpinEnd",
		"amount": 100,
		"winLevel": 1
	},
	"finalWin": {
		"index": 6,
		"type": "finalWin",
		"amount": 50
	}
} satisfies Record<string, BookEvent>;

export default events;
