import type { Bet } from '../../game/typesBookEvent';

// Generated by math-sdk/games/0_0_clash_of_kronos/storybook_fixtures.py.
// Edit the generator instead of this file.
type StorybookBet = Bet & { id: string; description: string; mode: 'base' | 'bonus' };

const books = [
	{
		"id": "base-no-win",
		"description": "Base spin with no line wins, scatters, or power-up wilds.",
		"bet": 100,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 2,
				"type": "finalWin",
				"amount": 0
			}
		],
		"mode": "base"
	},
	{
		"id": "golden-five-rune-middle",
		"description": "Regression: 5 RUNE on payline middle row (positions must match kind=5).",
		"bet": 100,
		"payoutMultiplier": 5.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 500,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 5,
						"win": 500,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 3,
								"row": 1
							},
							{
								"reel": 4,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 500,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 500
			},
			{
				"index": 4,
				"type": "setTotalWin",
				"amount": 500
			},
			{
				"index": 5,
				"type": "setWin",
				"amount": 500,
				"winLevel": 1
			},
			{
				"index": 6,
				"type": "finalWin",
				"amount": 500
			}
		],
		"mode": "base"
	},
	{
		"id": "base-one-line-stage-1",
		"description": "One winning cascade stays at tracker stage 1.",
		"bet": 100,
		"payoutMultiplier": 0.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "setTotalWin",
				"amount": 50
			},
			{
				"index": 5,
				"type": "setWin",
				"amount": 50,
				"winLevel": 1
			},
			{
				"index": 6,
				"type": "finalWin",
				"amount": 50
			}
		],
		"mode": "base"
	},
	{
		"id": "base-multi-line-stage-1",
		"description": "Multiple line wins in one cascade still count as stage 1.",
		"bet": 100,
		"payoutMultiplier": 1.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 150,
				"wins": [
					{
						"symbol": "HELMET",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 0
							},
							{
								"reel": 1,
								"row": 0
							},
							{
								"reel": 2,
								"row": 0
							}
						],
						"meta": {
							"lineIndex": 1,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					},
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 150
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 0
					},
					{
						"reel": 1,
						"row": 0
					},
					{
						"reel": 2,
						"row": 0
					},
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "setTotalWin",
				"amount": 150
			},
			{
				"index": 6,
				"type": "setWin",
				"amount": 150,
				"winLevel": 1
			},
			{
				"index": 7,
				"type": "finalWin",
				"amount": 150
			}
		],
		"mode": "base"
	},
	{
		"id": "base-two-cascades-stage-2",
		"description": "Two separate winning cascades advance to stage 2.",
		"bet": 100,
		"payoutMultiplier": 1.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "HELMET",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 0
							},
							{
								"reel": 1,
								"row": 0
							},
							{
								"reel": 2,
								"row": 0
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 8,
				"type": "setTotalWin",
				"amount": 150
			},
			{
				"index": 9,
				"type": "setWin",
				"amount": 150,
				"winLevel": 1
			},
			{
				"index": 10,
				"type": "finalWin",
				"amount": 150
			}
		],
		"mode": "base"
	},
	{
		"id": "base-stage-4-chests-unlock",
		"description": "Fourth winning cascade unlocks chest dollar values.",
		"bet": 100,
		"payoutMultiplier": 4.7,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 270,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 270,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 270,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						},
						"chestWins": [
							{
								"position": {
									"reel": 2,
									"row": 2
								},
								"amount": 120
							}
						]
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 270
			},
			{
				"index": 18,
				"type": "setTotalWin",
				"amount": 470
			},
			{
				"index": 19,
				"type": "setWin",
				"amount": 470,
				"winLevel": 2
			},
			{
				"index": 20,
				"type": "finalWin",
				"amount": 470
			}
		],
		"mode": "base"
	},
	{
		"id": "base-stage-5-2x",
		"description": "Base tracker reaches stage 5 and applies 2x.",
		"bet": 100,
		"payoutMultiplier": 4.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 18,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 19,
				"type": "cascadeTrackerUpdate",
				"stage": 5,
				"multiplier": 2,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 20,
				"type": "winInfo",
				"totalWin": 200,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 200,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 100,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 5,
							"trackerMultiplier": 2
						}
					}
				]
			},
			{
				"index": 21,
				"type": "updateTumbleWin",
				"amount": 200
			},
			{
				"index": 22,
				"type": "setTotalWin",
				"amount": 450
			},
			{
				"index": 23,
				"type": "setWin",
				"amount": 450,
				"winLevel": 2
			},
			{
				"index": 24,
				"type": "finalWin",
				"amount": 450
			}
		],
		"mode": "base"
	},
	{
		"id": "base-stage-6-3x",
		"description": "Base tracker reaches stage 6 and applies 3x.",
		"bet": 100,
		"payoutMultiplier": 7.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 18,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 19,
				"type": "cascadeTrackerUpdate",
				"stage": 5,
				"multiplier": 2,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 20,
				"type": "winInfo",
				"totalWin": 200,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 200,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 100,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 5,
							"trackerMultiplier": 2
						}
					}
				]
			},
			{
				"index": 21,
				"type": "updateTumbleWin",
				"amount": 200
			},
			{
				"index": 22,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 23,
				"type": "cascadeTrackerUpdate",
				"stage": 6,
				"multiplier": 3,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 24,
				"type": "winInfo",
				"totalWin": 300,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 300,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 3,
							"winWithoutMult": 100,
							"globalMult": 3,
							"lineMultiplier": 1,
							"trackerStage": 6,
							"trackerMultiplier": 3
						}
					}
				]
			},
			{
				"index": 25,
				"type": "updateTumbleWin",
				"amount": 300
			},
			{
				"index": 26,
				"type": "setTotalWin",
				"amount": 750
			},
			{
				"index": 27,
				"type": "setWin",
				"amount": 750,
				"winLevel": 3
			},
			{
				"index": 28,
				"type": "finalWin",
				"amount": 750
			}
		],
		"mode": "base"
	},
	{
		"id": "base-stage-7-5x",
		"description": "Base tracker reaches stage 7 and applies 5x.",
		"bet": 100,
		"payoutMultiplier": 12.5,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 18,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 19,
				"type": "cascadeTrackerUpdate",
				"stage": 5,
				"multiplier": 2,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 20,
				"type": "winInfo",
				"totalWin": 200,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 200,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 100,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 5,
							"trackerMultiplier": 2
						}
					}
				]
			},
			{
				"index": 21,
				"type": "updateTumbleWin",
				"amount": 200
			},
			{
				"index": 22,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 23,
				"type": "cascadeTrackerUpdate",
				"stage": 6,
				"multiplier": 3,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 24,
				"type": "winInfo",
				"totalWin": 300,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 300,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 3,
							"winWithoutMult": 100,
							"globalMult": 3,
							"lineMultiplier": 1,
							"trackerStage": 6,
							"trackerMultiplier": 3
						}
					}
				]
			},
			{
				"index": 25,
				"type": "updateTumbleWin",
				"amount": 300
			},
			{
				"index": 26,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 27,
				"type": "cascadeTrackerUpdate",
				"stage": 7,
				"multiplier": 5,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 28,
				"type": "winInfo",
				"totalWin": 500,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 500,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 5,
							"winWithoutMult": 100,
							"globalMult": 5,
							"lineMultiplier": 1,
							"trackerStage": 7,
							"trackerMultiplier": 5
						}
					}
				]
			},
			{
				"index": 29,
				"type": "updateTumbleWin",
				"amount": 500
			},
			{
				"index": 30,
				"type": "setTotalWin",
				"amount": 1250
			},
			{
				"index": 31,
				"type": "setWin",
				"amount": 1250,
				"winLevel": 4
			},
			{
				"index": 32,
				"type": "finalWin",
				"amount": 1250
			}
		],
		"mode": "base"
	},
	{
		"id": "base-lightning-wild",
		"description": "Lightning wild creates extra wilds before the next cascade.",
		"bet": 100,
		"payoutMultiplier": 2.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "WILD_LIGHTNING",
							"wild": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						},
						"powerUps": [
							"WILD_LIGHTNING"
						]
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "lightningStrike",
				"strikes": [
					{
						"position": {
							"reel": 1,
							"row": 2
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					},
					{
						"position": {
							"reel": 3,
							"row": 3
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					},
					{
						"position": {
							"reel": 4,
							"row": 1
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					}
				]
			},
			{
				"index": 6,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 7,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 8,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 9,
				"type": "setTotalWin",
				"amount": 200
			},
			{
				"index": 10,
				"type": "setWin",
				"amount": 200,
				"winLevel": 1
			},
			{
				"index": 11,
				"type": "finalWin",
				"amount": 200
			}
		],
		"mode": "base"
	},
	{
		"id": "base-surge-wild-active-chests",
		"description": "Surge wild increases active chest values after stage 4.",
		"bet": 100,
		"payoutMultiplier": 6.3,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "WILD_SURGE",
							"wild": true
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 120,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 120,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 120,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						},
						"powerUps": [
							"WILD_SURGE"
						]
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 120
			},
			{
				"index": 18,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 19,
				"type": "surgeChests",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"from": 75,
						"to": 125
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"from": 120,
						"to": 180
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"from": 200,
						"to": 300
					}
				]
			},
			{
				"index": 20,
				"type": "cascadeTrackerUpdate",
				"stage": 5,
				"multiplier": 2,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 21,
				"type": "winInfo",
				"totalWin": 360,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 360,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 180,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 5,
							"trackerMultiplier": 2
						},
						"chestWins": [
							{
								"position": {
									"reel": 2,
									"row": 2
								},
								"amount": 180
							}
						]
					}
				]
			},
			{
				"index": 22,
				"type": "updateTumbleWin",
				"amount": 360
			},
			{
				"index": 23,
				"type": "setTotalWin",
				"amount": 630
			},
			{
				"index": 24,
				"type": "setWin",
				"amount": 630,
				"winLevel": 3
			},
			{
				"index": 25,
				"type": "finalWin",
				"amount": 630
			}
		],
		"mode": "base"
	},
	{
		"id": "base-hammer-wild-smash",
		"description": "Hammer is collected from a win and consumed after a zero-win cascade.",
		"bet": 100,
		"payoutMultiplier": 2.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "WILD_HAMMER",
							"wild": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 4,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 4,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						},
						"powerUps": [
							"WILD_HAMMER"
						]
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 4,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "hammerCollect",
				"position": {
					"reel": 4,
					"row": 1
				}
			},
			{
				"index": 6,
				"type": "hammerSmash",
				"clearedPositions": [
					{
						"reel": 0,
						"row": 0
					},
					{
						"reel": 1,
						"row": 2
					},
					{
						"reel": 2,
						"row": 3
					},
					{
						"reel": 3,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "RUNE"
						}
					],
					[
						{
							"name": "SHIELD"
						}
					],
					[]
				],
				"resultBoard": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"trackerStage": 2,
				"trackerMultiplier": 1
			},
			{
				"index": 7,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 8,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 9,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 10,
				"type": "setTotalWin",
				"amount": 200
			},
			{
				"index": 11,
				"type": "setWin",
				"amount": 200,
				"winLevel": 1
			},
			{
				"index": 12,
				"type": "finalWin",
				"amount": 200
			}
		],
		"mode": "base"
	},
	{
		"id": "base-golden-eagle-wild",
		"description": "Golden eagle resolves lightning, surge, and hammer collect in sequence.",
		"bet": 100,
		"payoutMultiplier": 3.3,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "WILD_EAGLE",
							"wild": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 2,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 3,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 4,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 5,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 9,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": false
			},
			{
				"index": 10,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 11,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 12,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 13,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 1,
				"gameType": "basegame",
				"chestsActive": true
			},
			{
				"index": 14,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 15,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 16,
				"type": "winInfo",
				"totalWin": 180,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 180,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 180,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 1
						},
						"powerUps": [
							"WILD_EAGLE"
						]
					}
				]
			},
			{
				"index": 17,
				"type": "updateTumbleWin",
				"amount": 180
			},
			{
				"index": 18,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 19,
				"type": "lightningStrike",
				"strikes": [
					{
						"position": {
							"reel": 1,
							"row": 2
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					},
					{
						"position": {
							"reel": 3,
							"row": 3
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					}
				]
			},
			{
				"index": 20,
				"type": "surgeChests",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"from": 75,
						"to": 125
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"from": 120,
						"to": 180
					}
				]
			},
			{
				"index": 21,
				"type": "hammerCollect",
				"position": {
					"reel": 0,
					"row": 1
				}
			},
			{
				"index": 22,
				"type": "setTotalWin",
				"amount": 330
			},
			{
				"index": 23,
				"type": "setWin",
				"amount": 330,
				"winLevel": 2
			},
			{
				"index": 24,
				"type": "finalWin",
				"amount": 330
			}
		],
		"mode": "base"
	},
	{
		"id": "base-free-spin-trigger-3-scatters",
		"description": "Three scatters trigger eight free spins from base.",
		"bet": 100,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "basegame"
			},
			{
				"index": 1,
				"type": "freeSpinTrigger",
				"totalFs": 8,
				"positions": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 4,
						"row": 1
					}
				]
			},
			{
				"index": 2,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 3,
				"type": "finalWin",
				"amount": 0
			}
		],
		"mode": "base"
	}
] satisfies StorybookBet[];

export default books;
