import type { Bet } from '../../game/typesBookEvent';

// Generated by math-sdk/games/0_0_clash_of_kronos/storybook_fixtures.py.
// Edit the generator instead of this file.
type StorybookBet = Bet & { id: string; description: string; mode: 'base' | 'bonus' };

const books = [
	{
		"id": "bonus-no-win",
		"description": "Free spin with no win.",
		"bet": 100,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 0,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 3,
				"type": "finalWin",
				"amount": 0
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-stage-3-chests-unlock",
		"description": "Free spin tracker unlocks chests on stage 3.",
		"bet": 100,
		"payoutMultiplier": 2.7,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 1,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 3,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 4,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 5,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 6,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 7,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 8,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 9,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 10,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 11,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 12,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 13,
				"type": "winInfo",
				"totalWin": 170,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 170,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 170,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						},
						"chestWins": [
							{
								"position": {
									"reel": 2,
									"row": 2
								},
								"amount": 120
							}
						]
					}
				]
			},
			{
				"index": 14,
				"type": "updateTumbleWin",
				"amount": 170
			},
			{
				"index": 15,
				"type": "setTotalWin",
				"amount": 270
			},
			{
				"index": 16,
				"type": "setWin",
				"amount": 270,
				"winLevel": 2
			},
			{
				"index": 17,
				"type": "finalWin",
				"amount": 270
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-stage-4-2x",
		"description": "Free spin tracker applies 2x at stage 4.",
		"bet": 100,
		"payoutMultiplier": 4.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 2,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 3,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 4,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 5,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 6,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 7,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 8,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 9,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 10,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 11,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 12,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 13,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 14,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 15,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 16,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 2,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 17,
				"type": "winInfo",
				"totalWin": 200,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 200,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 100,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 2
						}
					}
				]
			},
			{
				"index": 18,
				"type": "updateTumbleWin",
				"amount": 200
			},
			{
				"index": 19,
				"type": "setTotalWin",
				"amount": 400
			},
			{
				"index": 20,
				"type": "setWin",
				"amount": 400,
				"winLevel": 2
			},
			{
				"index": 21,
				"type": "finalWin",
				"amount": 400
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-stage-7-10x",
		"description": "Free spin tracker applies 10x at stage 7.",
		"bet": 100,
		"payoutMultiplier": 22.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 3,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 75
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 120
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": true,
							"underlyingSymbol": "RUNE",
							"chestValue": 200
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 3,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 4,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 5,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 6,
				"type": "cascadeTrackerUpdate",
				"stage": 2,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 7,
				"type": "winInfo",
				"totalWin": 50,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 50,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 2,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 8,
				"type": "updateTumbleWin",
				"amount": 50
			},
			{
				"index": 9,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 10,
				"type": "cascadeTrackerUpdate",
				"stage": 3,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 11,
				"type": "chestUnlock",
				"positions": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 12,
				"type": "chestValuesUpdate",
				"updates": [
					{
						"position": {
							"reel": 0,
							"row": 3
						},
						"value": 75,
						"active": true
					},
					{
						"position": {
							"reel": 2,
							"row": 2
						},
						"value": 120,
						"active": true
					},
					{
						"position": {
							"reel": 4,
							"row": 2
						},
						"value": 200,
						"active": true
					}
				]
			},
			{
				"index": 13,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 3,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 14,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 15,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 16,
				"type": "cascadeTrackerUpdate",
				"stage": 4,
				"multiplier": 2,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 17,
				"type": "winInfo",
				"totalWin": 200,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 200,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 2,
							"winWithoutMult": 100,
							"globalMult": 2,
							"lineMultiplier": 1,
							"trackerStage": 4,
							"trackerMultiplier": 2
						}
					}
				]
			},
			{
				"index": 18,
				"type": "updateTumbleWin",
				"amount": 200
			},
			{
				"index": 19,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 20,
				"type": "cascadeTrackerUpdate",
				"stage": 5,
				"multiplier": 3,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 21,
				"type": "winInfo",
				"totalWin": 300,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 300,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 3,
							"winWithoutMult": 100,
							"globalMult": 3,
							"lineMultiplier": 1,
							"trackerStage": 5,
							"trackerMultiplier": 3
						}
					}
				]
			},
			{
				"index": 22,
				"type": "updateTumbleWin",
				"amount": 300
			},
			{
				"index": 23,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 24,
				"type": "cascadeTrackerUpdate",
				"stage": 6,
				"multiplier": 5,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 25,
				"type": "winInfo",
				"totalWin": 500,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 500,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 5,
							"winWithoutMult": 100,
							"globalMult": 5,
							"lineMultiplier": 1,
							"trackerStage": 6,
							"trackerMultiplier": 5
						}
					}
				]
			},
			{
				"index": 26,
				"type": "updateTumbleWin",
				"amount": 500
			},
			{
				"index": 27,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 28,
				"type": "cascadeTrackerUpdate",
				"stage": 7,
				"multiplier": 10,
				"gameType": "freegame",
				"chestsActive": true
			},
			{
				"index": 29,
				"type": "winInfo",
				"totalWin": 1000,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 1000,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 10,
							"winWithoutMult": 100,
							"globalMult": 10,
							"lineMultiplier": 1,
							"trackerStage": 7,
							"trackerMultiplier": 10
						}
					}
				]
			},
			{
				"index": 30,
				"type": "updateTumbleWin",
				"amount": 1000
			},
			{
				"index": 31,
				"type": "setTotalWin",
				"amount": 2200
			},
			{
				"index": 32,
				"type": "setWin",
				"amount": 2200,
				"winLevel": 4
			},
			{
				"index": 33,
				"type": "finalWin",
				"amount": 2200
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-retrigger-3-scatters",
		"description": "Three free-spin scatters retrigger five spins.",
		"bet": 100,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 4,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "freeSpinRetrigger",
				"totalFs": 5,
				"positions": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 4,
						"row": 1
					}
				]
			},
			{
				"index": 3,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 4,
				"type": "finalWin",
				"amount": 0
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-retrigger-4-scatters",
		"description": "Four free-spin scatters retrigger eight spins.",
		"bet": 100,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 5,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SCATTER",
							"scatter": true
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "freeSpinRetrigger",
				"totalFs": 8,
				"positions": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 4,
						"row": 1
					}
				]
			},
			{
				"index": 3,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 4,
				"type": "finalWin",
				"amount": 0
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-lightning-wild",
		"description": "Lightning wild works during free spins.",
		"bet": 100,
		"payoutMultiplier": 1.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 6,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "WILD_LIGHTNING",
							"wild": true
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 3,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						},
						"powerUps": [
							"WILD_LIGHTNING"
						]
					}
				]
			},
			{
				"index": 4,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 5,
				"type": "tumbleBoard",
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 2,
						"row": 1
					}
				],
				"newSymbols": [
					[
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "HELMET"
						}
					],
					[],
					[]
				]
			},
			{
				"index": 6,
				"type": "lightningStrike",
				"strikes": [
					{
						"position": {
							"reel": 1,
							"row": 2
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					},
					{
						"position": {
							"reel": 3,
							"row": 3
						},
						"toSymbol": {
							"name": "WILD",
							"wild": true
						}
					}
				]
			},
			{
				"index": 7,
				"type": "setTotalWin",
				"amount": 100
			},
			{
				"index": 8,
				"type": "setWin",
				"amount": 100,
				"winLevel": 1
			},
			{
				"index": 9,
				"type": "finalWin",
				"amount": 100
			}
		],
		"mode": "bonus"
	},
	{
		"id": "bonus-free-spin-end",
		"description": "Last free spin ends with the outro panel.",
		"bet": 100,
		"payoutMultiplier": 1.0,
		"events": [
			{
				"index": 0,
				"type": "updateFreeSpin",
				"amount": 7,
				"total": 8
			},
			{
				"index": 1,
				"type": "reveal",
				"board": [
					[
						{
							"name": "HELMET"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						}
					],
					[
						{
							"name": "SHIELD"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						}
					],
					[
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						}
					],
					[
						{
							"name": "EAGLE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "PEGASUS"
						},
						{
							"name": "RUNE"
						},
						{
							"name": "SHIELD"
						}
					],
					[
						{
							"name": "KRONOS_SMALL"
						},
						{
							"name": "SHIELD"
						},
						{
							"name": "CHEST",
							"chestActive": false,
							"underlyingSymbol": "RUNE"
						},
						{
							"name": "HELMET"
						},
						{
							"name": "HELMET"
						}
					]
				],
				"paddingPositions": [
					0,
					0,
					0,
					0,
					0
				],
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				],
				"gameType": "freegame"
			},
			{
				"index": 2,
				"type": "cascadeTrackerUpdate",
				"stage": 1,
				"multiplier": 1,
				"gameType": "freegame",
				"chestsActive": false
			},
			{
				"index": 3,
				"type": "winInfo",
				"totalWin": 100,
				"wins": [
					{
						"symbol": "RUNE",
						"kind": 3,
						"win": 100,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						],
						"meta": {
							"lineIndex": 2,
							"multiplier": 1,
							"winWithoutMult": 100,
							"globalMult": 1,
							"lineMultiplier": 1,
							"trackerStage": 1,
							"trackerMultiplier": 1
						}
					}
				]
			},
			{
				"index": 4,
				"type": "updateTumbleWin",
				"amount": 100
			},
			{
				"index": 5,
				"type": "setTotalWin",
				"amount": 100
			},
			{
				"index": 6,
				"type": "setWin",
				"amount": 100,
				"winLevel": 1
			},
			{
				"index": 7,
				"type": "freeSpinEnd",
				"amount": 100,
				"winLevel": 1
			},
			{
				"index": 8,
				"type": "finalWin",
				"amount": 100
			}
		],
		"mode": "bonus"
	}
] satisfies StorybookBet[];

export default books;
